title: J000K3Rs MOS Templates
description: Templates for the MOS Hub – a collection of templates that are directly discoverable inside the MOS Hub.
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://mos-templates.evil-corp.at"
baseurl: ""
logo: "/icons/logo.png"

search_enabled: true
color_scheme: dark
nav_sort: case_insensitive

footer_content: "MOS Templates – maintained by J000K3R"
